### ISSUE TITLE
Override configuration using env variables

### ISSUE THREAD

**Issue by adampetrovic** [innogames/slack-bot#15]
To support 12 factor, allow for environment variables to be passed as overrides to the underlying configuration. This is especially important for passing in secrets (Slack tokens, Jira passwords etc) as hardcoding them in the configuration file isn't ideal.

I have an implementation in my private fork that uses [viper](https://github.com/spf13/viper) at it's core. I'll clean it up and send a PR for your consideration :)

Let me know what you thinks?

**Comment by brainexe** [comment]
Sounds promising! Feel free to submit the PR. -------- Originalnachricht --------Betreff: [innogames/slack-bot] Override configuration using env variables (#15)Von: Adam Petrovic An: innogames/slack-bot Cc: Subscribed To support 12 factor, allow for environment variables to be passed as overrides to the underlying configuration. This is especially important for passing in secrets (Slack tokens, Jira passwords etc) as hardcoding them in the configuration file isn't ideal.
I have an implementation in my private fork that uses viper at it's core. I'll clean it up and send a PR for your consideration :)
Let me know what you thinks?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/innogames/slack-bot/issues/15?email_source=notifications\u0026email_token=AAOOO74L4QTIGZQ73D45KXLQY25IXA5CNFSM4J3CTP42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IATDVYQ",
"url": "https://github.com/innogames/slack-bot/issues/15?email_source=notifications\u0026email_token=AAOOO74L4QTIGZQ73D45KXLQY25IXA5CNFSM4J3CTP42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IATDVYQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by brainexe** [comment]
@adampetrovic  - Just found this issue after some time...in the meantime I already integrated viper with the option to set env vars, using the "BOT_" prefix

**Comment by brainexe** [comment]
you can overwrite any config value by the "BOT_*" env vars. For the correct name apply this simple rules:
- get the key name from the "map_structure" definition of the struct. else the just property name.
- uppercase everything
- delimiter for struct/nested access is "_"
- append the "BOT_" prefix

So for the slack->token it's BOT_SLACK_TOKEN


Hint: with "-show-config" you can dump the config. But there the config keys are named by the struct names and not using the map_structure name...

**Example usage:**
```
BOT_SLACK_TOKEN=123 BOT_SLACK_SOCKET_TOKEN=345 BOT_TIMEZONE=Europe/Berlin BOT_SLACK_DEBUG=true  ./build/slack-bot -show-config
slack:
    token: "123"
    sockettoken: "345"
    allowedgroups: []
    errorchannel: ""
    debug: true
timezone: Europe/Berlin
...
```
